version: '2'

services:
    frontend:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8080:80"
    backend:
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
            args: 
              JAR_FILE: build/libs/*.jar
        ports:
            - "3000:3000"
