# This workflow was not ultimately used due to github environment not playing nicely with the mock json-server. Except for connecting to localhost:3000 the pipeline runs fine but the integration tests fail without a working backend.

name: E2E tests
on: 
  push:
    branches: [ "feature/integration-tests" ]
    paths-ignore:
      - backend/**
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run mock, npm run serve
          browser: chrome
          wait-on: http://localhost:8080/
          config-file: cypress.json
          spec: "tests/e2e/**/*"
        env:
          CYPRESS_baseUrl: http://localhost:8080/
