name: Build Gradle project

on:
  push:
    branches:
      - master
      - feature/github-actions
    paths:
      - backend/**

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
